FROM node:16-alpine as build
WORKDIR /app
COPY ./ ./
RUN npm install -f --silent
RUN npm run build

FROM nginx:1.16-alpine
COPY --from=build ./app/build ./usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d

EXPOSE 80