FROM node:16-alpine as build
WORKDIR /app
COPY package*.json
RUN npm install --production -f --silent
RUN npm run build

FROM nginx:1.16-alpine
WORKDIR /app
COPY --build=build ./app/build ./
COPY ./nginx.conf ./app/

EXPOSE 80

CMD ["nginx", "-g", "daemon off"]